project_five/app_one/urls.py
from django.urls import path
from app_one import views

app_name = 'app_one'

urlpatterns = [
    path('',views.index, name='index'),
    path('other/',views.other, name='other'),
    path('relative/',views.relative, name='relative'),
]

project_five/project_five/urls.py
from django.contrib import admin
from django.urls import path, include
from app_one import views

urlpatterns = [
    path('',views.index, name='index'),
    path('admin/', admin.site.urls),
    path('app_one/',include('app_one.urls')),
]

project_five/app_one/models.py
from django.db import models

# Create your models here.

project_five/app_one/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    my_dict = {'text' : 'hello world', 'number':100}
    return render(request, 'app_one/index.html', context=my_dict)


def other(request):
    my_dict = {'insert_me' : 'OTHER'}
    return render(request, 'app_one/other.html', context=my_dict)


def relative(request):
    my_dict = {'insert_me' : 'RELATIVE URL'}
    return render(request, 'app_one/relative_url_templates.html', context=my_dict)

project_five/templates/app_one/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <div class='container'>
        <nav class='navbar navbar-static-top'>
            <div class='container'>
                <ul class='nav navbar-nav'>
                    <li><a class='navbar-brand' href="{% url 'index' %}">BRAND</a></li>
                    <li><a class='navbar-link'  href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class='navbar-link'  href="{% url 'app_one:other' %}">Other</a></li>
                </ul>
            </div>
        </nav>
    </div>


    <div class='container'>
        {% block body_block %}
        <!-- anything outside of this will be inherited -->
        {% endblock %}

    </div>
</body>
</html>

project_five/templates/app_one/index.html
<!DOCTYPE html>
{% extends 'app_one/base.html' %}
    {% block body_block %}
        <h1 class="display-4">Index :: Application One</h1>
        <p class="lead">{{ text|cut:'hello'}}</p>
        <p class="lead">{{ number|add:'99' }}</p>
    {% endblock %}

project_five/templates/app_one/other.html
<!DOCTYPE html>
{% extends 'app_one/base.html' %}
    {% block body_block %}
        <h1 class="display-4">Other :: Application One</h1>
        <p class="lead">{{ insert_me }}</p>
    {% endblock %}

project_five/templates/app_one/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Other :: Relative URLS</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <div class="jumbotron">
        <h1 class="display-4">Relative URL :: Application One</h1>
        <p class="lead">{{ insert_me }}</p>
        <a href="{% url 'app_one:other' %}">The Other Page</a>
        <a href="{% url 'app_one:index' %}">The Index Page</a>
        <a href="{% url 'admin:index' %}">The Admin Page</a>
        <a href="{% url 'index' %}">Index Page</a>
        <hr class="my-4">
    </div>   
</body>
</html>